#!/usr/bin/env bash

[[ -z $1 ]] && echo -e "\e[38;5;202mInvalid arugument: argument should be a file or url\e[m" >&2 && exit 1
arg="$1"
# arg="$HOME/Pictures/Wallpapers/aesthetic_wallpapers/4k-ai-mountain.jpg"

terminal="alacritty"
launcher="rofi -dmenu -l 1 -location 2 -p open-with"
. "$HOME/.config/prodigy/prodigy.conf"

mime_extract() {
    # extract general and specific part from mimetype
    mime_specifc="$(cut -d "/" -f 2 <<<"$1" | sed "s/-/_/g")"
    mime_general="$(cut -d "/" -f 1 <<<"$1" | sed "s/-/_/g")"

}
get_mime_ext() {

    # Getting mimetype from url protocol
    if ! [[ -e $arg ]]; then
        protocol_regex="^([a-zA-Z-]+):"
        if [[ $arg =~ $protocol_regex ]]; then
            protocol="${BASH_REMATCH[1]}"
            case "$protocol" in
            http) mime="x-scheme-handler/http" ;;
            https) mime="x-scheme-handler/https" ;;
            magnet) mime="x-scheme-handler/magnet" ;;
            mailto) mime="x-scheme-handler/mailto" ;;
            irc) mime="x-scheme-handler/irc" ;;
            *) mime="x-scheme-handler/https" ;; # Remove this if you want launcher for other urls
            esac
            mime_extract $mime
            return
        else
            echo -e "\e[38;5;202mInvalid arugument: argument should be a file or url\e[m" >&2 && exit 1
        fi
    fi

    # Getting mimetype and the first part of mimetype(text in text/plain)
    mime_extract $
    arg="$(realpath "$arg")"
    mime="$(file -b --mime-type "$arg")"
    mime_extract $mime
    # Getting the extension
    ext_regex='.*[.](.*[^.]$)'
    if [[ $arg =~ $ext_regex ]]; then
        ext="${BASH_REMATCH[1]}"
    fi

}
run_by_ext_mime() {

    ! [[ -e ~/.config/prodigy/prodigy.conf ]] && return
    [[ -z $program ]] && [[ -n $ext ]] && program=${!ext}
    [[ -z $program ]] && program=${!mime_specifc}
    [[ -z $program ]] && program=${!mime_general}

    [[ -n $program ]] && { setsid $program "$arg" & } && exit 0
}

run_by_desktop_file() {
    [[ -z $mime ]] && return

    desktop_files_paths=("/usr/share/applications" "$HOME/.local/share/applications")

    desktop_file_matches=$(for dir in "${desktop_files_paths[@]}"; do
        grep -RP -m 1 "^MimeType=.*${mime}" "$dir"
    done)

    [[ -z $desktop_file_matches ]] && return

    for match in $desktop_file_matches; do
        supported_mimes_count="$(cut -d ":" -f 2 <<<"$match" | grep -o "/" | wc -l)"
        file_name="$(cut -d ":" -f 1 <<<"$match")"
        # echo DEBUG "$supported_mimes_count" = "$file_name"
        desktop_files["$supported_mimes_count"]="$file_name"
    done

    desktop_file="${desktop_files[-1]}" # gets the program that supports most mimetypes

    program="$(grep -m 1 "^Exec=" "$desktop_file" | cut -d "=" -f 2 | cut -d " " -f 1)"
    [[ -z $program ]] && return

    grep "Terminal=true" "$desktop_file" &>/dev/null && {
        { setsid $terminal -e $program "$arg" & } && exit 0

    }
    { setsid $program "$arg" & } && exit 0

}

run_by_launcher() {

    program="$($launcher)"

    [[ -n $program ]] && { setsid $program "$arg" & } && exit 0 || exit 1
}

get_mime_ext

run_by_ext_mime
run_by_desktop_file
run_by_launcher
